[package]
name = "::name::"
version = "0.1.0"
edition = "2021"

[lib]
crate-type = ["cdylib"]

[dependencies]
# NOTE: uncomment line 11 and comment 12, if it's desirable to switch to published `near-sdk` version
# near-sdk = { default-features = false, ::sdk-cratesio-version-toml:: }
near-sdk = { default-features = false, ::sdk-git-version-toml:: }
serde = { version = "1", features = ["derive"] }

[workspace]
members = []

[profile.release]
codegen-units = 1
# Tell `rustc` to optimize for small code size.
opt-level = "z"
lto = true
debug = false
panic = "abort"
