[package]
name = "::name::"
version = "0.1.0"
edition = "2021"

[lib]
crate-type = ["cdylib"]

[dependencies]
near-sdk = "=4.0.0"
serde = { version = "1", features = ["derive"] }
schemars = "0.8"

# XXX: parity-secp256k1 was purged from crates.io, so we need to patch the old SDK with git dependency:
# See https://github.com/near/near-sdk-rs/issues/1126
[patch.crates-io]
parity-secp256k1 = {git = "https://github.com/paritytech/rust-secp256k1"}

[workspace]
members = []

[profile.release]
codegen-units = 1
# Tell `rustc` to optimize for small code size.
opt-level = "z"
lto = true
debug = false
panic = "abort"
