name: Release-plz

on:
  push:
    branches:
      - main

permissions: {}

jobs:
  release:
    uses: near/shared-workflows/.github/workflows/release-plz.yml@v1
    permissions:
      contents: write
      pull-requests: write
      id-token: write
      attestations: write
    with:
      apt-packages: libudev-dev
    secrets:
      pr-token: ${{ secrets.NEARPROTOCOL_CI_PR_ACCESS }}
      release-token: ${{ secrets.NEARPROTOCOL_CI_PR_ACCESS }}
